sudo: false
language: python
python:
  - 2.7

env:
  - DBNAME="weblog" DBUSER="postgres" DBPASS="" STATIC_ROOT="" MEDIA_ROOT=""

install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  - psql -c "CREATE DATABASE weblog;" -U postgres

script:
  - flake8 --exclude=migrations blog
  - ./manage.py test

notification:
  email: false