sudo: false
language: python
python:
  - 3.6
services:
  - postgresql
env:
  - DBNAME="weblog" DBUSER="postgres" DBPASS="" STATIC_ROOT="" MEDIA_ROOT="" SECRET_KEY="asdfg" AWS_STORAGE_BUCKET_NAME="blog-static"

install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  - psql -c "CREATE DATABASE weblog;" -U postgres

script:
  - flake8 --exclude=migrations blog
  - ./manage.py test --settings=weblog.settings.tests

notification:
  email: false